### ISSUE TITLE
Add humidity delta to reduce power cycling

### ISSUE THREAD

**Issue by joshuata** [adrianByv/home-assistant-custom-components-switch-humidifier#5]
It would be nice to expose a setting for a delta that would be added to the desired humidity level so that there is no chance the system will turn the switch on and off repeatedly. A default of `0.2` percent would probably be enough, it would just require waiting to turn off the system until it reached `goal + delta`, and then letting it drift until it dropped below (or above) the delta percentage again.

**Comment by ApoAdrian** [comment]
It was my next step. The question that arises me is whether to keep active until target + delta or until target and inactive until target - delta. What do you think @joshuata ?

**Comment by joshuata** [comment]
I think it depends on the type - if you are humidifying it should increase until target+delta and then fall until it hits the target, and if dehumidifying go until target - delta and then let humidity rise until target. That way it is always within the target zone, which I think makes more sense to the end user. I know it's annoying when I set the thermostat to 70 and see it reading 69, even if I understand why.

**Comment by ApoAdrian** [comment]
I'm implementing two params, start_delta and stop_delta. If you want to stop on target you can set stop to 0 and start to 0.2. Or int the other way set start to 0.2 and stop to 0. The default values are going to be 0.1 for both

I'll commit it later if I get some free time to finish it...

**Comment by joshuata** [comment]
Awesome. I'll take a look at the HACS errors and see if I can resolve them
