### ISSUE TITLE
Version key missing

### ISSUE THREAD

**Issue by slipperybeluga** [adrianByv/home-assistant-custom-components-switch-humidifier#6]
Just a friendly heads up, started noticing this message in my logs: 

`No 'version' key in the manifest file for custom integration 'switch_humidifier'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'switch_humidifier'`

**Comment by alextircovnicu** [comment]
@adrianByv  can be closed.

**Comment by ApoAdrian** [comment]
Solved with #7
